### ISSUE TITLE
Ctrl-click flips Number box to zero and back

### ISSUE THREAD

**Issue by aaaaalbert** [pd-externals/tipoftheday-plugin#22]
### Detail

```plain text
When in Run mode, click a Number box with the Ctrl or Alt key held down to set its value to zero immediately.

Ctrl-click or Alt-click again, and the previous value is restored.
```

### URL

http://msp.ucsd.edu/Pd_documentation/x2.htm#s1.3

### Image
![ctrl-click-number-box](https://user-images.githubusercontent.com/3806695/173199251-d80d9c03-f87c-4fc8-894c-f0d6fc0a37e5.gif)

**Comment by umlaeute** [comment]
wow, i didn't even know this tip :-)

re GIF: if you are fast enough, you could edit your initial report and insert the GIF under the `### Image` header.
this will (well: should) update the automatic PR #23 to include the image

**Comment by aaaaalbert** [comment]
I added the GIF, let's see what happens.

**Comment by aaaaalbert** [comment]
I just realized the tip is part of the help patch for Number boxes anyway, see [`doc/5.reference/gui-boxes-help.pd`](https://github.com/pure-data/pure-data/blob/master/doc/5.reference/gui-boxes-help.pd#L384-L387) (also known as `gatom-help.pd` before https://github.com/pure-data/pure-data/commit/417f045f6132b2938bf67b3f036aae01633994dd).

**Comment by aaaaalbert** [comment]
No problem, I'm not voting for removal, just wanted to tie the sources together.
