### ISSUE TITLE
Switch it off!

### ISSUE THREAD

**Issue by abreubacelar** [pd-externals/tipoftheday-plugin#3]
### Detail

```plain text
You can disable signal processing inside a subpatch or abstraction using [switch~] object! Just create a toggle and connect to it. Check its helpfile for more details!
```

### Image

![tip-switchItOff-1000](https://user-images.githubusercontent.com/16086370/172616737-934bf18d-36dd-45fb-8ed2-932f73baec9d.GIF)

**Comment by umlaeute** [comment]
please replace the MP4 with an animated GIF.
MP4s are just not supported in the final plugin.

**Comment by abreubacelar** [comment]
done! i'm not sure if it did the conversion correctly to 10 fps... still learning how to do this in kdenlive... if it is wrong i will try again
