### ISSUE TITLE
How to temporarily open pd without localization? (or a different one)

### ISSUE THREAD

**Issue by abreubacelar** [pd-externals/tipoftheday-plugin#38]
### Detail

```plain text
If for some reason you want to open pd ignoring your system language, you can open it in a terminal using

LANG=C pd

This will default to English version of pd, it is also possible to open pd in other languages this way, for example

"LANG=pt_BR pd" will open pd in Brazilian Portuguese 
"LANG=es pd" will open pd in Spanish
```

**Comment by umlaeute** [comment]
isn't this a duplicate of #34 ?
see  https://deken.puredata.info/tipoftheday-plugin/tips/wrong-language-linguaxe-incorrecta-khottii-bhaassaa/

the existing tip does not mention the "default" language though.

in any case, please note that the correct spelling of "pd" is "Pd" (but the command is called `pd`)

**Comment by abreubacelar** [comment]
oh true! i didn't check there was another one, i needed to use the specific LANG=C trick (you taught me this through irc once) and then i thought about creating the tip... i will close this one then!
