### ISSUE TITLE
Tab key to cycle through objects

### ISSUE THREAD

**Issue by umlaeute** [pd-externals/tipoftheday-plugin#43]
### Detail

```plain text
Select a single object and press the Tab key to cycle through the objects, message-boxes,...
```

### Image

![cycle-objects](https://user-images.githubusercontent.com/214034/235863408-b8a7fcd7-2e44-4a8c-9017-03ffae6440c5.gif)

**Comment by aaaaalbert** [comment]
Question (noted in #10): AFAICS, <kbd>Tab</kbd>-cycling only works when an object is selected in the first place. Is this on purpose?

**Comment by umlaeute** [comment]
that reminds me that you can also <kbd>Shift</kbd>+<kbd>Tab</kbd> to reverse-cycle the objects/connections/iolets...
